pool:
  vmImage: 'Ubuntu-18.04'

steps:
- script: |
    ls -la
    curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $(cat rust-toolchain) --profile=minimal
    echo "##vso[task.prependpath]$HOME/.cargo/bin"
  displayName: 'Install Rust'

- script: |
    sudo apt-get update
    sudo apt-get install -y --no-install-recommends build-essential libmariadb-dev-compat libpq-dev libssl-dev pkgconf
  displayName: 'Install build libraries.'

- script: |
    rustc -Vv
    cargo -V
  displayName: Query rust and cargo versions

- script : cargo test --features "sqlite,mysql,postgresql"
  displayName: 'Test project with sqlite, mysql and postgresql backends'
